Repository UCSB-VRL/bisqueUCSB, pull requests merged in 2025-01, with the labels that each got.

#80 Charvi/build devel amil ubuntu16.04
  Dockerfile
  README.md
  run-bisque.sh
  source/requirements.txt
Labels: bug, enhancement

#87 Update README.md
  README.md
Labels: bug

#88 :sparkles: Updated BisQue logo
  source/bqcore/bq/core/public/images/bisque_logo_gray.svg
  source/bqcore/bq/core/public/images/bisque_logo_gray_OLD.svg
Labels: enhancement
